version: '3.8'

services:
  db:
    container_name: furia_postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER:  furia_user
      POSTGRES_PASSWORD: furia_password
      POSTGRES_DB: furia_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

volumes:
  postgres_data:

networks:
  postgres-compose-network:
    driver: bridge
